api:
  parking:
    ettelbruck: https://iot.rms.lu/opendata/parking/ettelbruck
    luxembourg: https://feed.vdl.lu/circulation/parking/feed.json
    esch:
      data: https://esch.lu/wp-admin/admin-ajax.php?action=esch_parkings
      name: https://esch.lu/wp-admin/admin-ajax.php?action=esch_panels&panel=traffic
  charging_stations:
    chargy: https://my.chargy.lu/b2bev-external-services/resources/kml?API-KEY=486ac6e4-93b8-4369-9c6a-28f7c4e1a81f
  bikes:
    luxembourg: https://api.jcdecaux.com/vls/v3/stations/?contract=Luxembourg